name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 3.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.3.7
  quiver: ^3.2.1
  # xml: ^6.2.2
  xml: ^5.0.0
  image: ^3.0.4
  collection: ^1.17.0

dev_dependencies:
  test: ^1.16.7
  path: ^1.8.0
  pedantic: ^1.11.0
